divert(-1)
define(comment)
define(loc, 0) coment(`location counter')
define(iconst_m1, `define(`loc', eval(loc + 1))dnl') 
define(iconst_0, `define(`loc', eval(loc + 1))dnl')
define(iconst_1, `define(`loc', eval(loc + 1))dnl') 
define(iconst_2, `define(`loc', eval(loc + 1))dnl')
define(iconst_3, `define(`loc', eval(loc + 1))dnl')
define(iconst_4, `define(`loc', eval(loc + 1))dnl')
define(iconst_5, `define(`loc', eval(loc + 1))dnl')
define(bipush, `define(`loc', eval(loc + 2))dnl')

define(iload_0, `define(`loc', eval(loc + 1))dnl')
define(iload_1, `define(`loc', eval(loc + 1))dnl')
define(iload_2, `define(`loc', eval(loc + 1))dnl')
define(iload_3, `define(`loc', eval(loc + 1))dnl')
define(iload, `define(`loc', eval(loc + 2))dnl')

define(istore_0, `define(`loc', eval(loc + 1))dnl')
define(istore_1, `define(`loc', eval(loc + 1))dnl')
define(istore_2, `define(`loc', eval(loc + 1))dnl')
define(istore_3, `define(`loc', eval(loc + 1))dnl')
define(istore, `define(`loc', eval(loc + 2))dnl')

define(pop, `define(`loc', eval(loc + 1))dnl')
define(swap, `define(`loc', eval(loc + 1))dnl')
define(dup, `define(`loc', eval(loc + 1))dnl')

define(iadd, `define(`loc', eval(loc + 1))dnl')
define(isub, `define(`loc', eval(loc + 1))dnl')
define(imul, `define(`loc', eval(loc + 1))dnl')
define(idiv, `define(`loc', eval(loc + 1))dnl')
define(irem, `define(`loc', eval(loc + 1))dnl')
define(ineg, `define(`loc', eval(loc + 1))dnl')
define(iinc, `define(`loc', eval(loc + 3))dnl')

define(jsr,  `define(`loc', eval(loc + 2))dnl')
define(ret,  `define(`loc', eval(loc + 1))dnl')

define(ifeq, `define(`loc', eval(loc + 2))dnl')
define(ifge, `define(`loc', eval(loc + 2))dnl')
define(ifgt, `define(`loc', eval(loc + 2))dnl')
define(ifle, `define(`loc', eval(loc + 2))dnl')
define(iflt, `define(`loc', eval(loc + 2))dnl')
define(ifne, `define(`loc', eval(loc + 2))dnl')
define(goto, `define(`loc', eval(loc + 2))dnl')

define(invokevirtual, `define(`loc', eval(loc + 2))dnl')
define(return, `define(`loc', eval(loc + 1))dnl')
define(label, ``define($1, 'eval(loc)`)'')
divert
include(java_input.m)
